#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# If nix isn't installed, assume we want the MacOS approach
if [ ! -d /nix/store ]
then
    echo "Installing dependencies..."

    npm install

    echo "Running tests..."

    npm test

else
    echo "Running tests..."
    script/nix-npm test
fi
